packages:
  - apps/*
  - packages/*
catalog:
  next: ^16.0.7
  "@trpc/server": ^11.5.0
  "@trpc/client": ^11.5.0
  "@trpc/tanstack-react-query": ^11.5.0
  "@tanstack/react-query": ^5.85.5
  dotenv: ^17.2.2
  zod: ^4.1.13
